// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddToWatchlist(arg1:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetStatus():Promise<main.Status>;

export function GetVersion():Promise<string>;

export function RemoveFromWatchlist(arg1:string):Promise<void>;

export function SaveSettings(arg1:number,arg2:number):Promise<void>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetPaused(arg1:boolean):Promise<void>;

export function SetTimeout(arg1:string,arg2:number):Promise<void>;

export function Snooze(arg1:string,arg2:number):Promise<void>;
